// form types
export const INPUT = "input"
export const INPUT_MASK = "input_mask"
export const TEXTAREA = "textarea"
export const ASYNC_SELECT = "async_select"
export const SELECT = "select"
export const CREATABLE_SELECT = "creatable_select"
export const CREATABLE_SELECT_WITH_MODAL = "creatable_select_with_modal"
export const CHECKBOX = "checkbox"
export const CHECKBOX_GROUP = "checkbox_group"
export const RADIO = "radio"
export const DATE_PICKER = "date_picker"
export const TIME_PICKER = "time_picker"
export const WYSIWYG_EDITOR = "wysiwyg_editor"
export const UPLOAD = "upload"
export const PRELOADED_TABLE = "preloaded_table"
export const MULTISELECT_TABLE = "multiselect_table"
export const WEEK_PICKER = "week_picker"

// display types
export const ITEM = "item"
export const LIST_OF_ITEMS = "list_of_items"
export const NESTED_LIST_OF_ITEMS = "nested_list_of_items"
export const TABLE_OF_ITEMS  = "table_of_items"

// menu types
export const LINK = "link"
export const DOWNLOAD_LINK = "download_link"
export const NESTED_LINKS = "nested_links"
export const SEPARATOR = "separator"
